apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{k8s_name}}
spec:
  dnsNames:
    - {{name}}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  secretName: {{k8s_name}}-tls
---
{{#has_extra_hostnames}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{k8s_name}}-extra
spec:
  dnsNames:
{{#extra_hostnames}}
    - {{hostname}}
{{/extra_hostnames}}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  secretName: {{k8s_name}}-extra-tls
{{/has_extra_hostnames}}
