apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{k8s_name}}
spec:
  dnsNames:
    - {{name}}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
  secretName: {{k8s_name}}-tls
