apiVersion: ecrpublic.aws.m.upbound.io/v1beta1
kind: Repository
metadata:
  name: {{name}}
  annotations:
    crossplane.io/external-name: {{name}}
spec:
  forProvider:
    region: us-east-1
    catalogData:
      description: Official images built from https://github.com/portswigger/{{name}} main
