{{#enable_charts}}
apiVersion: ecrpublic.aws.m.upbound.io/v1beta1
kind: Repository
metadata:
  name: charts-{{name}}
  annotations:
    crossplane.io/external-name: charts/{{name}}
spec:
  forProvider:
    region: us-east-1
    catalogData:
      description: Helm charts for https://github.com/portswigger/{{name}}
{{/enable_charts}}
